[build]
targets = ["release", "debug"]
default = "debug"

[runs]
cargo = "cargo"

[target.release]
result = "target/release/adamantite"
files = ["Cargo.toml", "src/main.rs"]
cmds = ["cargo build --release"]

[target.debug]
result = "target/debug/adamantite"
files = ["Cargo.toml", "src/main.rs"]
cmds = ["cargo build"]
